### PR TITLE
add authors to the browsable info

### PR DESCRIPTION
**Pull request by maelle**
For people looking for reviewers for instance

### CODE REVIEW

**Comment by bearloga** [comment]
I like this! Before I merge, can you please make the authors field optional the way description & URL are? (Reason being that some packages' authors lists can get very long so I don't want those to mess up the default experience.)

**Comment by maelle** [comment]
Done! I also noticed I had broken the app, well the indices were no longer the right ones... should be ok now.

**Comment by bearloga** [comment]
Thank you!

**Comment by maelle** [comment]
Thank *you*!

**Pull request merged**
